services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DB_HOST: mysql
      DB_USER: restaurant
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: res_booking

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0

    environment:
      MYSQL_DATABASE: res_booking
      MYSQL_USER: restaurant
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - "./database res_booking.sql:/docker-entrypoint-initdb.d/res_booking.sql:ro"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: